version: '3.7'

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  db:
    ports:
      - '6010:5432'
    volumes:
      - studybites-test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
  s3:
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
  api:
    command: yarn test:integration
    ports:
      - '6011:3017'
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      PORT: ${API_PORT}
      DATABASE_URL: ${POSTGRES_TEST_URI}

volumes:
  studybites-test:
