version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.dev
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SB_ADMIN_EMAIL: ${SB_ADMIN_EMAIL}
      SB_ADMIN_PASSWORD: ${SB_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
