version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: .docker/Dockerfile.dev
    ports:
      - '3018:3018'
    environment:
      PORT: ${FRONT_PORT}
      API_PORT: ${API_PORT}

networks:
  intranet:
